allow running wiremock in HTTPS
gitkent/helm-charts pull request #16
Opened 2022-04-18 04:57 UTC by alexsatori

With the following value overrides it will run successfully in HTTPS:

wiremock:
  scheme: "HTTPS"
  env: 
    WIREMOCK_OPTIONS: "--https-port=9021,--max-request-journal=1000,--local-response-templating,--root-dir=/home/wiremock/storage"

2022-04-26 10:49 UTC, gitkent approved these changes

2022-04-26 10:52 UTC, gitkent requested changes
Hi @alexsatori  thanks for your contribution. In order for us to merge into `master`, can you please sign your commit. See [here](https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification) for instructions.

2022-04-26 11:28 UTC, alexsatori commented
> Hi @alexsatori thanks for your contribution. In order for us to merge into `master`, can you please sign your commit. See [here](https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification) for instructions.

Done

2022-04-27 23:21 UTC, gitkent approved these changes

2022-04-27 23:21 UTC, merged